In [29]:
import numpy as np
import pandas as pd

In [30]:
df = pd.read_csv("letter-recognition.data")

In [31]:
df

       T  2   8  3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
0      I  5  12  3  7  2   10   5  5  4   13   3    9    2    8    4   10
1      D  4  11  6  8  6   10   6  2  6   10   3    7    3    7    3    9
2      N  7  11  6  6  3    5   9  4  6    4   4   10    6   10    2    8
3      G  2   1  3  1  1    8   6  6  6    6   5    9    1    7    5   10
4      S  4  11  5  8  3    8   8  6  9    5   6    6    0    8    9    7
...   .. ..  .. .. .. ..  ...  .. .. ..  ...  ..  ...  ...  ...  ...  ...
19994  D  2   2  3  3  2    7   7  7  6    6   6    4    2    8    3    7
19995  C  7  10  8  8  4    4   8  6  9   12   9   13    2    9    3    7
19996  T  6   9  6  7  5    6  11  3  7   11   9    5    2   12    2    4
19997  S  2   3  4  2  1    8   7  2  6   10   6    8    1    9    5    8
19998  A  4   9  6  6  2    9   5  3  1    8   1    8    2    7    2    8

[19999 rows x 17 columns]

In [32]:
df.head()

   T  2   8  3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
0  I  5  12  3  7  2   10   5  5  4   13   3    9    2    8    4   10
1  D  4  11  6  8  6   10   6  2  6   10   3    7    3    7    3    9
2  N  7  11  6  6  3    5   9  4  6    4   4   10    6   10    2    8
3  G  2   1  3  1  1    8   6  6  6    6   5    9    1    7    5   10
4  S  4  11  5  8  3    8   8  6  9    5   6    6    0    8    9    7

In [33]:
df.tail()

       T  2   8  3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
19994  D  2   2  3  3  2    7   7  7  6    6   6    4    2    8    3    7
19995  C  7  10  8  8  4    4   8  6  9   12   9   13    2    9    3    7
19996  T  6   9  6  7  5    6  11  3  7   11   9    5    2   12    2    4
19997  S  2   3  4  2  1    8   7  2  6   10   6    8    1    9    5    8
19998  A  4   9  6  6  2    9   5  3  1    8   1    8    2    7    2    8

In [34]:
df.shape

(19999, 17)

In [35]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [36]:
x

       2   8  3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
0      5  12  3  7  2   10   5  5  4   13   3    9    2    8    4   10
1      4  11  6  8  6   10   6  2  6   10   3    7    3    7    3    9
2      7  11  6  6  3    5   9  4  6    4   4   10    6   10    2    8
3      2   1  3  1  1    8   6  6  6    6   5    9    1    7    5   10
4      4  11  5  8  3    8   8  6  9    5   6    6    0    8    9    7
...   ..  .. .. .. ..  ...  .. .. ..  ...  ..  ...  ...  ...  ...  ...
19994  2   2  3  3  2    7   7  7  6    6   6    4    2    8    3    7
19995  7  10  8  8  4    4   8  6  9   12   9   13    2    9    3    7
19996  6   9  6  7  5    6  11  3  7   11   9    5    2   12    2    4
19997  2   3  4  2  1    8   7  2  6   10   6    8    1    9    5    8
19998  4   9  6  6  2    9   5  3  1    8   1    8    2    7    2    8

[19999 rows x 16 columns]

In [37]:
y

0        I
1        D
2        N
3        G
4        S
        ..
19994    D
19995    C
19996    T
19997    S
19998    A
Name: T, Length: 19999, dtype: object

In [38]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [39]:
y

array([ 8,  3, 13, ..., 19, 18,  0])

In [40]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [41]:
scalar = StandardScaler()

x_train = scalar.fit_transform(x_train)
x_test = scalar.fit_transform(x_test)

In [42]:
import tensorflow as tf;
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [43]:
model = Sequential()
model.add(Dense(128,activation='relu',input_shape=(16,)))
model.add(Dense(64,activation='relu'))
model.add(Dense(26,activation='softmax'))

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [44]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [45]:
history = model.fit(
    x_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.1
)

Epoch 1/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.4363 - loss: 2.0998 - val_accuracy: 0.7613 - val_loss: 0.8175
Epoch 2/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7857 - loss: 0.7280 - val_accuracy: 0.8150 - val_loss: 0.5957
Epoch 3/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8474 - loss: 0.5261 - val_accuracy: 0.8456 - val_loss: 0.4919
Epoch 4/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8725 - loss: 0.4360 - val_accuracy: 0.8737 - val_loss: 0.4161
Epoch 5/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8983 - loss: 0.3601 - val_accuracy: 0.8875 - val_loss: 0.3542
Epoch 6/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9051 - loss: 0.3088 - val_accuracy: 0.8906 - val_loss: 0.3292
Epoch 7/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9207 - loss: 0.2673 - val_accuracy: 0.9112 - val_loss: 0.2922
Epoch 8/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9288 - loss: 0.2346 - val_accuracy: 0.9187 - val_loss: 0.2695
Epoch 9/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9355 - loss: 0.2179 - val_accuracy: 0.9225 - val_loss: 0.2437
Epoch 10/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9391 - loss: 0.1945 - val_accuracy: 0.9206 - val_loss: 0.2517
Epoch 11/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9503 - loss: 0.1687 - val_accuracy: 0.9256 - val_loss: 0.2140
Epoch 12/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9545 - loss: 0.1561 - val_accuracy: 0.9337 - val_loss: 0.2100
Epoch 13/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9568 - loss: 0.1419 - val_accuracy: 0.9400 - val_loss: 0.1969
Epoch 14/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9620 - loss: 0.1284 - val_accuracy: 0.9356 - val_loss: 0.2125
Epoch 15/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.9606 - loss: 0.1283 - val_accuracy: 0.9369 - val_loss: 0.1826
Epoch 16/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9669 - loss: 0.1144 - val_accuracy: 0.9463 - val_loss: 0.1721
Epoch 17/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9683 - loss: 0.1061 - val_accuracy: 0.9375 - val_loss: 0.1728
Epoch 18/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9698 - loss: 0.0977 - val_accuracy: 0.9413 - val_loss: 0.1730
Epoch 19/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9706 - loss: 0.0963 - val_accuracy: 0.9488 - val_loss: 0.1591
Epoch 20/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.9715 - loss: 0.0886 - val_accuracy: 0.9400 - val_loss: 0.1678

In [46]:
loss,accuracy = model.evaluate(x_test,y_test)

print("Accuracy: ",accuracy)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9421 - loss: 0.1724
Accuracy:  0.9449999928474426

In [49]:
prediction = model.predict(x_test)
print(prediction[0])

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[6.3194688e-07 3.9897550e-06 6.1441774e-08 6.9207656e-10 3.0982338e-07
 1.6793515e-10 2.8937893e-06 2.2838629e-05 1.7168668e-05 1.7615355e-08
 2.3275589e-04 1.2085966e-06 1.8707888e-13 3.8838547e-11 6.5976544e-11
 7.0336230e-11 6.7594947e-09 2.6235991e-04 6.1619896e-09 1.1480933e-08
 2.0741107e-09 4.8415951e-09 4.1445873e-16 9.9945575e-01 1.8336365e-12
 3.7973255e-10]

In [50]:
predicted_class = np.argmax(prediction[0])

print(predicted_class)

23

In [51]:
letter = encoder.inverse_transform([predicted_class])

print(letter)

['X']